version: '3'
services:

    dynamodb:
        image: amazon/dynamodb-local
        ports:
          - '8000:8000'

    sqs_service:
        image: roribio16/alpine-sqs:latest
        ports:
            - '9324:9324'
            - '9325:9325'
